'use client';

import { useState } from 'react';
import useSWR from 'swr';
import { Download, Power, Save, ShieldAlert } from 'lucide-react';
import { EmptyState, SectionCard } from '@/components/PageChrome';

type Controls={brokerProvider:'none'|'IBKR'|'Alpaca';executionMode:'disabled'|'paper'|'live';killSwitch:boolean;schedule:'manual'|'hourly'|'daily'|'weekdays';timezone:'UTC'|'Asia/Kolkata'|'America/New_York'|'Europe/London';approvalPolicy:'manual'|'risk_gated';confidenceFloor:number|null;maxDailyLossPct:number|null;maxNotional:number|null;maxContracts:number|null;staleQuoteSeconds:number|null;emailAlerts:boolean;updatedAt:string};
const fetcher=async(url:string)=>{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('Unavailable');return r.json()};
const select='w-full rounded-md border border-[#cfd7eb] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#3d52da]';
export default function CustomerControlCenter(){const {data,mutate,isLoading}=useSWR<{controls:Controls|null;reason?:string}>('/api/customer/controls',fetcher);
  if(isLoading)return <SectionCard className="p-6"><div className="text-sm text-[#647269]">Loading deployment controls...</div></SectionCard>;
  if(!data?.controls)return <EmptyState title="Control center not provisioned" body={data?.reason||'A commercial customer record is required before deployment controls can be saved.'}/>;
  return <ControlForm key={data.controls.updatedAt} initial={data.controls} onSaved={()=>mutate()}/>;
}
function ControlForm({initial,onSaved}:{initial:Controls;onSaved:()=>void}){const [form,setForm]=useState<Controls>(initial);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);async function save(){setSaving(true);setMessage('');const r=await fetch('/api/customer/controls',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const body=await r.json();setSaving(false);if(!r.ok){setMessage(body.error||'Unable to save controls');return}setForm(body.controls);setMessage('Controls saved. Broker onboarding and live activation still require approval.');onSaved()}
  const set=<K extends keyof Controls>(key:K,value:Controls[K])=>setForm({...form,[key]:value});
  return <SectionCard className="overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#e2e7fb] px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-[#3d52da]">Deployment controls</div><h2 className="mt-2 text-2xl font-semibold text-[#06130c]">Broker, scheduler, risk, and alerts</h2></div><div className="flex gap-2"><a href="/api/customer/audit-export" className="inline-flex items-center gap-2 rounded-md border border-[#cbd5ff] px-3 py-2 text-sm font-semibold text-[#172554]"><Download className="h-4 w-4"/>Audit CSV</a><button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-md bg-[#172554] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving...':'Save controls'}</button></div></div>
  <div className="grid gap-px bg-[#e2e7fb] lg:grid-cols-3"><Panel title="Broker and mode"><Select label="Broker provider" value={form.brokerProvider} options={['none','IBKR','Alpaca']} onChange={v=>set('brokerProvider',v as Controls['brokerProvider'])}/><Select label="Execution mode" value={form.executionMode} options={['disabled','paper','live']} onChange={v=>set('executionMode',v as Controls['executionMode'])}/><Toggle label="Kill switch engaged" checked={form.killSwitch} onChange={v=>set('killSwitch',v)} icon={<Power/>}/></Panel><Panel title="Schedule and approval"><Select label="Schedule" value={form.schedule} options={['manual','hourly','daily','weekdays']} onChange={v=>set('schedule',v as Controls['schedule'])}/><Select label="Timezone" value={form.timezone} options={['UTC','Asia/Kolkata','America/New_York','Europe/London']} onChange={v=>set('timezone',v as Controls['timezone'])}/><Select label="Approval policy" value={form.approvalPolicy} options={['manual','risk_gated']} onChange={v=>set('approvalPolicy',v as Controls['approvalPolicy'])}/></Panel><Panel title="Risk limits"><NumberField label="Confidence floor (0-1)" value={form.confidenceFloor} onChange={v=>set('confidenceFloor',v)}/><NumberField label="Maximum daily loss (%)" value={form.maxDailyLossPct} onChange={v=>set('maxDailyLossPct',v)}/><NumberField label="Maximum notional (USD)" value={form.maxNotional} onChange={v=>set('maxNotional',v)}/><NumberField label="Maximum contracts" value={form.maxContracts} onChange={v=>set('maxContracts',v)}/><NumberField label="Stale quote threshold (seconds)" value={form.staleQuoteSeconds} onChange={v=>set('staleQuoteSeconds',v)}/><Toggle label="Email alerts" checked={form.emailAlerts} onChange={v=>set('emailAlerts',v)} icon={<ShieldAlert/>}/></Panel></div>{message?<div className={`border-t px-5 py-3 text-sm font-semibold ${message.startsWith('Controls')?'border-[#bbf7d0] bg-[#f0fdf4] text-[#047857]':'border-[#fecaca] bg-[#fef2f2] text-[#be123c]'}`}>{message}</div>:null}<div className="border-t border-[#e2e7fb] bg-[#f8faff] px-5 py-3 text-xs leading-5 text-[#647269]">Broker credentials are never entered here. Provider authorization is completed through a separate server-side onboarding process. Live execution remains approval-gated.</div></SectionCard>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="grid content-start gap-4 bg-white p-5"><h3 className="font-semibold text-[#06130c]">{title}</h3>{children}</div>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="grid gap-1.5 text-xs font-bold uppercase tracking-wide text-[#647269]">{label}<select className={select} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function NumberField({label,value,onChange}:{label:string;value:number|null;onChange:(v:number|null)=>void}){return <label className="grid gap-1.5 text-xs font-bold uppercase tracking-wide text-[#647269]">{label}<input className={select} type="number" min="0" step="any" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/></label>}
function Toggle({label,checked,onChange,icon}:{label:string;checked:boolean;onChange:(v:boolean)=>void;icon:React.ReactNode}){return <label className="flex items-center justify-between gap-4 rounded-md border border-[#e2e7fb] px-3 py-2.5"><span className="inline-flex items-center gap-2 text-sm font-semibold text-[#26352c] [&>svg]:h-4 [&>svg]:w-4">{icon}{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-[#3d52da]"/></label>}
