'use client';

import { useState } from 'react';
import { Activity, Pause, Play, RotateCcw, ShieldCheck } from 'lucide-react';
import { SectionCard } from '@/components/PageChrome';

const scenarios = {
  steady: { label:'Steady signal', confidence:72, exposure:38, drawdown:-1.8, status:'Paper monitoring' },
  volatile: { label:'Volatility event', confidence:41, exposure:0, drawdown:-4.6, status:'Risk gate flattened' },
  stale: { label:'Stale market data', confidence:0, exposure:0, drawdown:-1.2, status:'Execution blocked' },
};

export default function SandboxDemo(){const [key,setKey]=useState<keyof typeof scenarios>('steady');const [running,setRunning]=useState(true);const s=scenarios[key];return <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><SectionCard className="p-5"><div className="text-xs font-bold uppercase tracking-wide text-[#647269]">Scenario</div><div className="mt-4 grid gap-2">{Object.entries(scenarios).map(([id,row])=><button key={id} onClick={()=>setKey(id as keyof typeof scenarios)} className={`rounded-md border px-3 py-3 text-left text-sm font-semibold ${key===id?'border-[#3d52da] bg-[#eef2ff] text-[#172554]':'border-[#e2e7fb] text-[#5a685f]'}`}>{row.label}</button>)}</div><div className="mt-5 flex gap-2"><button aria-label={running?'Pause demo':'Run demo'} onClick={()=>setRunning(!running)} className="flex h-10 w-10 items-center justify-center rounded-md bg-[#172554] text-white">{running?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}</button><button aria-label="Reset demo" onClick={()=>{setKey('steady');setRunning(true)}} className="flex h-10 w-10 items-center justify-center rounded-md border border-[#cbd5ff] text-[#172554]"><RotateCcw className="h-4 w-4"/></button></div></SectionCard><SectionCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#e2e7fb] px-6 py-4"><div><div className="text-xs font-bold uppercase tracking-wide text-[#3d52da]">Synthetic sandbox</div><h2 className="mt-1 text-xl font-semibold text-[#06130c]">Execution-readiness preview</h2></div><span className={`h-2.5 w-2.5 rounded-full ${running?'bg-[#3d52da]':'bg-[#94a3b8]'}`}/></div><div className="grid gap-px bg-[#e2e7fb] sm:grid-cols-4"><Metric icon={<Activity/>} label="Confidence" value={`${s.confidence}%`}/><Metric icon={<ShieldCheck/>} label="Exposure" value={`${s.exposure}%`}/><Metric icon={<Activity/>} label="Drawdown" value={`${s.drawdown}%`}/><Metric icon={<ShieldCheck/>} label="Control state" value={s.status}/></div><div className="p-6"><div className="h-44 border-b border-l border-[#cbd5ff] bg-[linear-gradient(to_right,rgba(61,82,218,.07)_1px,transparent_1px),linear-gradient(to_bottom,rgba(61,82,218,.07)_1px,transparent_1px)] bg-[size:52px_44px]"><div className="flex h-full items-end gap-2 p-4">{[34,48,44,61,s.exposure,53,67,72].map((v,i)=><div key={i} className="flex-1 bg-[#3d52da] transition-all" style={{height:`${running?v:18}%`,opacity:.35+i*.07}}/>)}</div></div><p className="mt-4 text-sm leading-6 text-[#5a685f]">All values on this page are synthetic and exist only to demonstrate interface behavior. They are not investment results, live signals, or model recommendations.</p></div></SectionCard></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="min-h-28 bg-white p-4"><span className="block text-[#3d52da] [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div className="mt-3 text-xs uppercase tracking-wide text-[#647269]">{label}</div><div className="mt-2 text-lg font-semibold text-[#06130c]">{value}</div></div>}
